steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-west2-docker.pkg.dev/stellar-lock-399303/nextjs-docker-front2-floodforec-docker-repo/nextjs-docker-front2-floodforec-image:prd",
        ".",
      ]
  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-west2-docker.pkg.dev/stellar-lock-399303/nextjs-docker-front2-floodforec-docker-repo/nextjs-docker-front2-floodforec-image:prd",
      ]
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "nextjs-docker-front2-floodforec-image",
        "--image",
        "us-west2-docker.pkg.dev/stellar-lock-399303/nextjs-docker-front2-floodforec-docker-repo/nextjs-docker-front2-floodforec-image:prd",
        "--region",
        "us-west2",
      ]
images:
  - "us-west2-docker.pkg.dev/stellar-lock-399303/nextjs-docker-front2-floodforec-docker-repo/nextjs-docker-front2-floodforec-image:prd"
